##########################################
# Site Settings

baseURL = "https://quotes.ulsterworldly.com/"
title = "Miscellanea"
author = "Tim Hopper"
copyright = "Copyright Â© 2021, ulsterworldly.com."
languageCode = "en-US"
theme = "ezhil"

[outputFormats.JSONRSS]
mediaType = "application/json"
baseName = "index"
isPlainText = false
isHTML = false
noUgly = true

[outputs]
home = ["HTML", "RSS", "JSONRSS"]

# Taxonomies
[taxonomies]
    author = "authors"
    tag = "tags"

[[menu.main]]
name = "Introduction"
url = "/"
weight = 1

[[menu.main]]
name = "All Quotes"
url = "/q/"
weight = 2

[[menu.main]]
name = "Authors"
url = "/authors/"
weight = 3

[[menu.main]]
name = "Topics"
url = "/tags/"
weight = 3


# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Collected quotes from reading in theology, history, and more."
  subtitle = "Buy the truth, and sell it not; also wisdom, and instruction, and understanding. (Proverbs 23)"

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Miscellanea"

